<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\DynamicLocalization.WPF\DynamicLocalization.WPF.csproj"/>
        <ProjectReference Include="..\..\src\DynamicLocalization.DependencyInjection\DynamicLocalization.DependencyInjection.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Localization\*.json"/>
    </ItemGroup>

</Project>
