using System.Globalization;
using Avalonia.DynamicLocalization.Providers;
using CommunityToolkit.Mvvm.ComponentModel;

namespace Avalonia.DynamicLocalization.Core;

/// <summary>
/// Default implementation of language service managing multiple localization providers.
/// </summary>
/// <remarks>
/// <para>
/// This class implements <see cref="ILanguageService"/> and supports:
/// </para>
/// <list type="bullet">
///   <item><description>Multiple providers working together, searching in registration order</description></item>
///   <item><description>Automatic notification to all subscribers when language changes</description></item>
///   <item><description>Culture fallback mechanism (zh-CN -> zh -> default)</description></item>
/// </list>
/// </remarks>
public partial class LanguageService : ObservableObject, ILanguageService
{
    private readonly List<ILocalizationProvider> _providers = new();
    private CultureInfo _currentLanguage;
    private List<CultureInfo>? _availableLanguages;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(CurrentLanguage))]
    private CultureInfo _currentLanguageField;

    /// <summary>
    /// Gets or sets the current language.
    /// </summary>
    /// <remarks>
    /// <para>When setting a new language:</para>
    /// <list type="number">
    ///   <item><description>Updates <see cref="CultureInfo.CurrentUICulture"/> and <see cref="CultureInfo.DefaultThreadCurrentUICulture"/></description></item>
    ///   <item><description>Triggers <see cref="LanguageChanged"/> event</description></item>
    /// </list>
    /// </remarks>
    public CultureInfo CurrentLanguage
    {
        get => CurrentLanguageField;
        set
        {
            if (CurrentLanguageField != value)
            {
                var oldLanguage = _currentLanguage;
                _currentLanguage = value;
                CultureInfo.CurrentUICulture = value;
                CultureInfo.DefaultThreadCurrentUICulture = value;
                CurrentLanguageField = value;
                OnLanguageChanged(value, oldLanguage);
            }
        }
    }

    /// <summary>
    /// Gets all available languages.
    /// </summary>
    /// <remarks>
    /// This list is generated by merging and deduplicating cultures from all registered
    /// <see cref="ILocalizationProvider"/> instances. Results are cached until a provider
    /// is registered or unregistered.
    /// </remarks>
    public IReadOnlyList<CultureInfo> AvailableLanguages
    {
        get
        {
            if (_availableLanguages == null)
            {
                _availableLanguages = _providers
                    .SelectMany(p => p.GetAvailableCultures())
                    .Distinct()
                    .ToList();
            }
            return _availableLanguages;
        }
    }

    /// <summary>
    /// Indexer for quick access to localized strings.
    /// </summary>
    /// <param name="key">The localization key.</param>
    /// <returns>The localized string, or #key# format if not found.</returns>
    public string this[string key] => GetString(key);

    /// <summary>
    /// Occurs when the current language changes.
    /// </summary>
    public event EventHandler<LanguageChangedEventArgs>? LanguageChanged;

    /// <summary>
    /// Creates a language service instance using the current thread's UI culture as default.
    /// </summary>
    public LanguageService()
    {
        _currentLanguage = CultureInfo.CurrentUICulture;
        _currentLanguageField = _currentLanguage;
    }

    /// <summary>
    /// Gets the localized string for the specified key using the current language.
    /// </summary>
    public string GetString(string key)
    {
        return GetString(key, _currentLanguage);
    }

    /// <summary>
    /// Gets the localized string for the specified key and culture.
    /// </summary>
    /// <remarks>
    /// <para>Search order:</para>
    /// <list type="number">
    ///   <item><description>Iterate all providers in registration order, return first match</description></item>
    ///   <item><description>If current culture is not in available list, try first available culture</description></item>
    ///   <item><description>If still not found, return #key# format</description></item>
    /// </list>
    /// </remarks>
    public string GetString(string key, CultureInfo? culture)
    {
        culture ??= _currentLanguage;

        foreach (var provider in _providers)
        {
            if (provider.TryGetString(key, culture, out var value) && value != null)
            {
                return value;
            }
        }

        if (AvailableLanguages.Count > 0 && !AvailableLanguages.Contains(culture))
        {
            var fallbackCulture = AvailableLanguages[0];
            foreach (var provider in _providers)
            {
                if (provider.TryGetString(key, fallbackCulture, out var value) && value != null)
                {
                    return value;
                }
            }
        }

        return $"#{key}#";
    }

    /// <summary>
    /// Gets a formatted localized string.
    /// </summary>
    /// <param name="key">The localization key.</param>
    /// <param name="args">Format arguments.</param>
    /// <returns>The formatted string.</returns>
    public string Format(string key, params object[] args)
    {
        var format = GetString(key);
        return string.Format(_currentLanguage, format, args);
    }

    /// <summary>
    /// Registers a localization provider.
    /// </summary>
    /// <param name="provider">The provider to register.</param>
    /// <remarks>
    /// Registration invalidates the available languages cache; it will be recalculated on next access.
    /// </remarks>
    public void RegisterProvider(ILocalizationProvider provider)
    {
        _providers.Add(provider);
        _availableLanguages = null;
    }

    /// <summary>
    /// Unregisters a localization provider by name.
    /// </summary>
    /// <param name="providerName">The provider name (e.g., "Json", "Resx").</param>
    public void UnregisterProvider(string providerName)
    {
        _providers.RemoveAll(p => p.Name == providerName);
        _availableLanguages = null;
    }

    /// <summary>
    /// Raises the language changed event.
    /// </summary>
    protected virtual void OnLanguageChanged(CultureInfo newLanguage, CultureInfo oldLanguage)
    {
        LanguageChanged?.Invoke(this, new LanguageChangedEventArgs(newLanguage, oldLanguage));
    }
}
